# declaring x
x = 10

# declaring y
y = 10

# adding x and y
z = x + y * (y-x)

if x > y
    print "x is greater"
else if x < y
    print "y is greater"
else
    print "x and y are equal"

i = 100
while i <= 110
    print "The value of i is" i
    i = i+1
end

cpp{
    int a = 34;
    for (int i = a; i<a+5; i++){
        cout << "The value of a is " << a << endl;
    }
}

# printing the values
print x "+" y "is" x+y